branches:
  except:
    - gh-pages
language: perl
sudo: false
perl:
#  - "blead"
  - "5.22"
  - "5.20"
  - "5.18"
before_install:
  - cd perl
  - eval $(curl https://travis-perl.github.io/init) --auto

